### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by nickheyer** [jellyfin/jellyfin-apiclient-python#32]
I'm curious how it is expected for users to understand the usages of an api wrapper like this without providing documentation. The readme provides a single example and suggests that users refer to two other repos for API usage.

The first repo relating to Jellyfin transcoding and the second repo does eventually link to the official jellyfin api documentation, but that doesn't help at all when you've created a wrapper that is inherently intended to abstract away the boilerplate code for making api requests to a jellyfin server.

Am I missing something? If I am, I apologize, but either way please consider being more clear on this subject.

**Comment by iwalton3** [comment]
You're unfortunately not missing anything. The purpose of this repo was to make a publishable version of the API client which I ripped out of the Jellyfin for Kodi project. I haven't taken the time to document the existing library, however I am committed to not breaking it since applications depend on it.

Contributions for API docs are encouraged. I personally don't have the free time and energy to dedicate to documenting this library right now, sadly.

**Comment by nickheyer** [comment]
> You're unfortunately not missing anything. The purpose of this repo was to make a publishable version of the API client which I ripped out of the Jellyfin for Kodi project. I haven't taken the time to document the existing library, however I am committed to not breaking it since applications depend on it.
> 
> Contributions for API docs are encouraged. I personally don't have the free time and energy to dedicate to documenting this library right now, sadly.

No worries, I can relate to side-project maintenance grind. Thanks for the response.
